tools:
  - name: "neovim"
    description: "Setup NeoVim"
    conflict: "error"
    linkmap:
      windows:
        - "nvim/init.vim": "$LOCALAPPDATA/nvim/init.vim"

  - name: "powershell"
    os: ["windows"]
    description: "Setup Powershell"
    conflict: "error"
    linkmap:
      - "powershell/Microsoft.PowerShell_profile.ps1": "$USERPROFILE/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"
      - "powershell/oh-my-posh-theme.omp.json": "$USERPROFILE/Documents/WindowsPowerShell/oh-my-posh-theme.omp.json"

  - name: "vscode"
    description: "Setup Visual Studio"
    conflict: "error"
    linkmap:
      windows:
        - "vscode/keybindings.json": "$USERPROFILE/AppData/Roaming/Code/User/keybindings.json"
        - "vscode/settings.json": "$USERPROFILE/AppData/Roaming/Code/User/settings.json"
    post-link:
      - name: "install-extensions"
        is-path: true
        cmd: ["./vscode/install-extensions.bat"]
    maintenace:
      - name: "collect-extensions"
        is-path: true
        cmd: ["./vscode/get-extensions.bat"]